# This file is generated by ./gen-sources.sh.
# Do not edit!
{
  targetCommit = "1bc4296091c51f53a5598050c8956d16e945b0f5";
  files = {
    "sysa/bash-2.05b/mk/builtins.mk" = "0939dy5by1xhfmsjj6w63nlgk509fjrhpb2crics3dpcv7prl8lj";
    "sysa/bash-2.05b/mk/common.mk" = "09rigxxf85p2ybnq248sai1gdx95yykc8jmwi4yjx389zh09mcr8";
    "sysa/bash-2.05b/mk/main.mk" = "0hj29q3pq3370p18sxkpvv9flb7yvx2fs96xxlxqlwa8lkimd0j4";
    "sysa/bash-2.05b/patches/dev-tty.patch" = "1315slv5f7ziajqyxg4jlyanf1xwd06xw14y6pq7xpm3jzjk55j9";
    "sysa/bash-2.05b/patches/locale.patch" = "1p1q1slhafsgj8x4k0dpn9h6ryq5fwfx7dicbbxhldbw7zvnnbx9";
    "sysa/bash-2.05b/patches/mes-libc.patch" = "0zksdjf6zbb3p4hqg6plq631y76hhhgab7kdvf7cnpk8bcykn12z";
    "sysa/bash-2.05b/patches/missing-defines.patch" = "1q0k1kj5mrvjkqqly7ki5575a5b3hy1ywnmvhrln318yh67qnkj4";
    "sysa/bash-2.05b/patches/tinycc.patch" = "042d2kr4a8klazk1hlvphxr6frn4mr53k957aq3apf6lbvrjgcj2";
    "sysa/flex-2.5.11/files/scan.lex.l" = "0ilwrhvq02r6kf7rbf0c7b2664nwiaq0zd6g7waz0qmr27f1pij4";
    "sysa/flex-2.5.11/mk/main.mk" = "0nghqg6yibxwiiylcqsjyv0bdpdi8nfcf6k5hbbcq7054fcha3b4";
    "sysa/flex-2.5.11/patches/scan_l.patch" = "0bs2af6wzi1ih10jyhmhcfplmqi1jcz0r3gsmimi14lh9lwmmama";
    "sysa/flex-2.5.11/patches/yyin.patch" = "01fhfi80pldw7wk52dswagc10xwbf78wxfnwllfb78mahzbwal1b";
    "sysa/gzip-1.2.4/files/stat_override.c" = "1216xn1536mfjyx9j1b6128ynb3mfdmy68h7y0n656sk9p5rpf75";
    "sysa/gzip-1.2.4/mk/main.mk" = "06c9xl13ym41i2q7rb370kc7affwxbbm6lyqpgbpj6q83bv4dhkq";
    "sysa/sed-4.0.9/mk/main.mk" = "0w1f5ri0g5zla31m6l6xyzbqwdvandqfnzrsw90dd6ak126w3mya";
    "sysa/tar-1.12/files/getdate_stub.c" = "0i0j6ymksqf6ip82yqw7j4qwzyc580j2d7wsdf41p8nvg9dmaw4n";
    "sysa/tar-1.12/files/stat_override.c" = "1ald02j1c15nhs865bwl17lqcy45mrr8n5j0bhhnxkah1bnhimrz";
    "sysa/tar-1.12/mk/main.mk" = "0iqidqns4j452pcsh9zr3pbgr2y128xxrl1fz7v1rj7d5zhij1h4";
  };
}
