# This file is generated by ./gen-sources.sh.
# Do not edit!
{
  "1bc4296091c51f53a5598050c8956d16e945b0f5" = {
    files = [
      "sysa/bash-2.05b/mk/builtins.mk"
      "sysa/bash-2.05b/mk/common.mk"
      "sysa/bash-2.05b/mk/main.mk"
      "sysa/bash-2.05b/patches/dev-tty.patch"
      "sysa/bash-2.05b/patches/locale.patch"
      "sysa/bash-2.05b/patches/mes-libc.patch"
      # "sysa/bash-2.05b/patches/missing-defines.patch" # wont fetch?
      "sysa/bash-2.05b/patches/tinycc.patch"
    ];
    sha256 = "0s7spx3jbmflp8vr0hkr466nwn92wy56r0wxx4lmkrdp7a6hs8mc";
  };
  "d918b984ad6fe4fc7680f3be060fd82f8c9fddd9" = {
    files = [
      "sysa/heirloom-devtools-070527/patches/lex_remove_wchar.patch"
      "sysa/heirloom-devtools-070527/patches/yacc_remove_wchar.patch"
    ];
    sha256 = "04rgxyidppmkkgp5spf05m3884cz30m09d9wwf0hmphsk7bb93cr";
  };
  "e86db47b6ee40d68e26866dd15e8637f64d6d778" = {
    files = [
      "sysa/coreutils-5.0/mk/main.mk"
      # "sysa/coreutils-5.0/patches/expr-strcmp.patch" # wont fetch?
      "sysa/coreutils-5.0/patches/ls-strcmp.patch"
      "sysa/coreutils-5.0/patches/mbstate.patch"
      "sysa/coreutils-5.0/patches/modechange.patch"
      "sysa/coreutils-5.0/patches/sort-locale.patch"
      "sysa/coreutils-5.0/patches/touch-dereference.patch"
      "sysa/coreutils-5.0/patches/touch-getdate.patch"
    ];
    sha256 = "14bdxyg16ngcw53mfvjq2khqrdf2f3zp0r3fgwdgg63dzi4wkf0b";
  };
}
